before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        export MAKE=mingw32-make
        ;;
      *)
        export MAKE=make
        ;;
    esac
dist: focal
language: go
go:
- 1.15.x
script:
- $MAKE
branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.\\d+/"
matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
before_deploy:
- $MAKE
deploy:
  provider: releases
  api_key:
    secure: oPoYBXA8T3bHhmrE4HCspARWPrQbVzwUVii/9AzC5fMtueG3+HfgB+6UVwJ8A1fmsypM4hO2J3uA8hZguQDJnOKMJs7j6iCf44P567dZh8ROvlC0JQZJV2dDXj7EQ9I3Pc70bZKLv/TTnszlc5+yQkmi9UsnSoJygfC9myp5fgLN0KOsp+05rHaQGTJaW85zRmZ3nElnfUOB5WBMu3d88ji6ieTBPurd2fP6xHEE+yoPmmrZR2jGAhzCEZad7RQJKEw21dyp8+3A6SD3AkW0TrFtg33MAraJHtDiorg27H0ghnq+SnD0S4YZR29jLDYL8M8dqREuYRU985l4S2RyxphrF3j2aZpqXFvS8xzRQFP89uwOjVUUm76XiEGN7nuwSyjLTQShRfPP3jHIOepvhLG+y1buDhmEjRO0iDcNny9q49Hu8EC3fEHBMEwlGhr6BEElNkUDqhp39S2pbG6GZblIQyR1+VUzBS9I2/gvFQNyzJCkM4+8diwYVHmP3FNcP2o01d1Le41s562BhNlOkJmM2S/jMk83I8UO1xfVQ6zYBsaAoH2CszzyVkL6TGJqxxpGKc3saQ6ZEtr/8knm9lkeseAzpoJAnwBaI/RJUh5Tft89ehXMGQhIJSJZr+M9Lg38ZNKXhhab4RPDCT3za4rJVGrmd+dLqQljyUVZ+Zg=
  file_glob: true
  file: 'bin/*'
  on:
    tags: true
    repo: kayrus/gof5
  skip_cleanup: 'true'
